### ISSUE TITLE
CGUITTFont updates

### ISSUE THREAD

**Issue by mercury233** [mzeilfelder/irr-playground-micha#1]
I just discovered you had maintained a release of `CGUITTFont`, and I'm very glad to hear that because `CGUITTFont` is used in a project (https://github.com/Fluorohydride/ygopro) which I contributed to.

What I want to say is I found a glitch: https://github.com/Fluorohydride/ygopro/pull/2305
> ![image](https://user-images.githubusercontent.com/13391795/83966733-a01a9180-a8ee-11ea-9d60-133336d9c6e1.png)
With some font, here is overwritten by other char.
Correct:
![image](https://user-images.githubusercontent.com/13391795/83966826-3353c700-a8ef-11ea-862d-4197d48a0ed8.png)

Can you check my changes?

What is more, some another people made changes to `CGUITTFont` too. What I know are:
https://github.com/arch-jslin/Irrlicht/blob/cubeat-irrlicht/source/Irrlicht/CGUITTFont.cpp
https://github.com/edo9300/edopro/blob/master/gframe/CGUITTFont/CGUITTFont.cpp

Them have much differences, maybe you will found something useful to your version.

**Comment by mzeilfelder** [comment]
Thanks. There have also been many changes in my version of those files by now. Will probably take a while until I get to this patch.

**Comment by mzeilfelder** [comment]
I made some changes in be6927b. Not sure if it also fixes your problem as I don't know which font you use. So if you could give me a the font + example text you used to produce the bug I could test.

**Comment by mercury233** [comment]
sorry i can't test it because my version of CGUITTFont had removed `max_font_height` and `lineHeight`

the font is [sarasa-ui-sc-regular](https://github.com/be5invis/Sarasa-Gothic)

**Comment by mzeilfelder** [comment]
Thanks. That part of the code is too different in my version already. I think my version creates one texture per character and then pages them later. Maybe we already started with different versions of this code.
There is some other bug which can lead to a similar problem. Draw can overwrite characters currently (while static-box using getDimension works correct with my new fixes). I might get back to that one later.
